services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_SITE_GRIDPAGESIZE=100
      - ME_CONFIG_SITE_MAXITEMS=100
      - ME_CONFIG_SITE_GRIDFS_ENABLED=true
      - ME_CONFIG_SITE_GRIDFS_MAXPAGES=100
    depends_on:
      - mongodb
    command: sh -c "sleep 10 && /docker-entrypoint.sh mongo-express"
